export const metadata = {
  title: 'eCommerce app| Products',
  description: 'Generated by create next app',
};
export default function RootLayout({ children }) {
  return (
    <div>
      <h3>Product Layout</h3>
      {children}
    </div>
  );
}
